# Generated by Django 6.1 on 2026-08-21 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=30)),
                ('dphno', models.IntegerField()),
                ('demail', models.EmailField(max_length=254)),
                ('dspec', models.CharField()),
                ('davail', models.BooleanField()),
                ('dpassword', models.CharField(default=None)),
                ('doc_pic', models.ImageField(blank=True, null=True, upload_to='images')),
                ('doc_intro', models.FileField(blank=True, null=True, upload_to='videos')),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField()),
                ('pphno', models.IntegerField()),
                ('pemail', models.EmailField(max_length=254)),
                ('page', models.IntegerField()),
                ('pat_pic', models.ImageField(blank=True, null=True, upload_to='images')),
                ('pat_symp', models.FileField(blank=True, null=True, upload_to='audio')),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appoint_date', models.DateField()),
                ('appoint_time', models.TimeField()),
                ('document', models.FileField(blank=True, null=True, upload_to='documents')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.doctors')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.patients')),
            ],
        ),
    ]
